import { Header } from '@/components/Header/Header'
import { cn } from '@/services/utils/cn'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'

//need to change
const inter = Inter({ subsets: ['latin'] })

//need to change
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='uk' className='h-full'>
			<head />
			<body
				className={cn(
					'relative flex flex-col min-h-screen font-sans antialiased',
					inter.className
				)}
			>
				<div className='wrapper'>
					<Header />
					<main className='relative flex-1'>{children}</main>
					<footer className='p-8 mt-auto'>Footer</footer>
				</div>
			</body>
		</html>
	)
}
