import type { Metadata } from 'next'
import React from 'react'
import ClientRootLayout from './ClientRootLayout'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='uk' className='h-full'>
			<head />
			<body className='relative flex flex-col min-h-screen font-pangram antialiased'>
				<ClientRootLayout>{children}</ClientRootLayout>
			</body>
		</html>
	)
}
