// app/layout.tsx

import Footer from '@/components/Footer/Footer'
import { Header } from '@/components/Header/Header'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='uk' className='h-full'>
			<head />
			<body className='relative wrapper h-full font-pangram antialiased'>
				<Header />
				<main className='relative flex-1'>{children}</main>
				<Footer />
				<div id='modal-root'></div>
			</body>
		</html>
	)
}
