export { default as LogoIcon } from './Logo.svg'
export { default as ArrowLeftIcon } from './arrow-left.svg'
export { default as CartIcon } from './cart.svg'
export { default as CloseIcon } from './close.svg'
export { default as ModalMenuIcon } from './mob-menu.svg'
export { default as SearchIcon } from './search.svg'
export { default as UserIcon } from './user.svg'
